/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/views/Article/index.vue')['default']
    ArticleCate: typeof import('./src/views/Write/components/ArticleCate.vue')['default']
    ArticleDate: typeof import('./src/views/Write/components/ArticleDate.vue')['default']
    ArticleTag: typeof import('./src/views/Write/components/ArticleTag.vue')['default']
    Cate: typeof import('./src/views/Cate/index.vue')['default']
    Columnar: typeof import('./src/components/Columnar/index.vue')['default']
    Date: typeof import('./src/components/Date/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTree: typeof import('element-plus/es')['ElTree']
    Header: typeof import('./src/views/Layout/components/Header.vue')['default']
    HeaderInfo: typeof import('./src/views/Home/components/HeaderInfo.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Home: typeof import('./src/views/Home/index.vue')['default']
    Layout: typeof import('./src/views/Layout/index.vue')['default']
    Linear: typeof import('./src/views/Home/components/Linear.vue')['default']
    Login: typeof import('./src/views/Login/index.vue')['default']
    My: typeof import('./src/views/Setup/components/My.vue')['default']
    Recording: typeof import('./src/views/Home/components/Recording.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./src/views/Setup/index.vue')['default']
    Sidebar: typeof import('./src/views/Layout/components/Sidebar.vue')['default']
    Site: typeof import('./src/views/Setup/components/Site.vue')['default']
    Swiper: typeof import('./src/views/Swiper/index.vue')['default']
    SwiperAdd: typeof import('./src/views/Swiper/components/SwiperAdd.vue')['default']
    SwiperList: typeof import('./src/views/Swiper/components/SwiperList.vue')['default']
    Tag: typeof import('./src/views/Tag/index.vue')['default']
    Tags3D: typeof import('./src/views/Tag/components/Tags3D.vue')['default']
    Title: typeof import('./src/components/Title/index.vue')['default']
    Write: typeof import('./src/views/Write/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
