/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElRow: typeof import('element-plus/es')['ElRow']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Home: typeof import('./src/views/Home/index.vue')['default']
    Layout: typeof import('./src/views/Layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/views/Layout/components/Sidebar.vue')['default']
  }
}
